name: Postcard Poems
author: Caroline Whitehouse
description: "A poetry postcard blog. Original work of poems inspired by
  photographs, enjoy reading the weekly blogs and go on a journey of discovery.
  Based in Deal Kent "
metaImage: /img/2024-a-1-.png
url: https://postcardpoems.co.uk
image: /img/logo-svg.svg
width: "266.56"
height: "103.04"
