name: Postcard Poems
description: A poetry blog with postcards
image: /img/logo-svg.svg
metaImage: /img/derp-cat.jpeg
url: https://postcardpoems.co.uk
author: Caroline Whitehouse
width: "400"
height: "400"
