name: Postcard Poems
author: Caroline Whitehouse
description: A poetry postcard blog. Original work to take you on a journey of
  discovery. Based in Deal Kent
metaImage: /img/beyond-pebbles-face-kingsdown.jpg
url: https://postcardpoems.co.uk
image: /img/logo-svg.svg
width: "266.56"
height: "103.04"
