name: Postcard Poems
author: Caroline Whitehouse
description: A poetry blog with postcards based in Deal, Kent
metaImage: /img/dog-stamp.jpg
url: https://postcardpoems.co.uk
image: /img/logo-svg.svg
width: "400"
height: "400"
